USE [master]
GO

/****** Object:  Database [PRUEBA_SEBASTIAN]    Script Date: 7/24/2019 19:12:45 ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'PRUEBA_SEBASTIAN')
BEGIN
CREATE DATABASE [PRUEBA_SEBASTIAN]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRUEBA_SEBASTIAN', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PRUEBA_SEBASTIAN.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PRUEBA_SEBASTIAN_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PRUEBA_SEBASTIAN_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
END
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRUEBA_SEBASTIAN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET ARITHABORT OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET  MULTI_USER 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PRUEBA_SEBASTIAN] SET  READ_WRITE 
GO

USE [PRUEBA_SEBASTIAN]
GO

/****** Object:  Schema [Store]    Script Date: 7/24/2019 19:13:52 ******/
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'Store')
EXEC sys.sp_executesql N'CREATE SCHEMA [Store]'
GO
